package ua.vasylenko.main.agent.ontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sat Oct 07 21:28:33 EEST 2017 by Тёма
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/тёма/ontologies/2017/9/untitled-ontology-11#Link
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LINK.<p>
     * 
     */
    public static final OWLClass CLASS_LINK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/тёма/ontologies/2017/9/untitled-ontology-11#Link"));


}
