package ua.vasylenko.main.agent.ontology.impl;

import ua.vasylenko.main.agent.ontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLink <br>
 * @version generated on Sat Oct 07 21:28:33 EEST 2017 by Тёма
 */
public class DefaultLink extends WrappedIndividualImpl implements Link {

    public DefaultLink(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
